---

- name: "rsync testssl.sh (directory, distribution)"
  synchronize: 
    src: testssl.sh
    dest: /usr/local/share/
    delete: yes
    rsync_opts:
      - "--exclude=.git"

- name: Copy wrapper scripts
  copy:
    src: "{{ item }}"
    dest: /usr/lib/zabbix/externalscripts/
    mode: 0755
  loop:
    - mit-check-cert.py
    - mit-check-cert.sh
    - mit-testssl.sh

- name: Install python-pip
  apt: pkg=python-pip

- name: Install pyzabbix via pip
  pip: name=pyzabbix

- name: "Copy zabbix-mit-testssl-caller"
  copy: src=zabbix-mit-testssl-caller dest=/usr/local/bin/ mode=755

- name: "Copy cronjob"
  copy: src=local-zabbix-mit-testssl-caller dest=/etc/cron.d/

