---

- name: "rsync testssl.sh (directory, distribution)"
  synchronize: 
    src: testssl.sh/
    dest: /usr/local/share/testssl.sh/
    delete: yes
    rsync_opts:
      - "--exclude=.git"

- name: Copy wrapper scripts
  copy:
    src: "{{ item }}"
    dest: /usr/lib/zabbix/externalscripts/
    mode: 0755
  loop:
    - mit-check-cert.py
    - mit-check-cert.sh

- name: Install python-pip
  apt:
    pkg: python-pip

- name: Install pyzabbix via pip
  pip:
    name: pyzabbix

- name: Copy zabbix-mit-testssl*
  copy:
    src: "{{ item}}"
    dest: /usr/local/bin/
    mode: 0755    
  loop:
    - zabbix-mit-testssl
    - zabbix-mit-testssl-caller
    - zabbix-mit-testssl-helper

- name: "Copy cronjob"
  copy:
    src: local-zabbix-mit-testssl-caller
    dest: /etc/cron.d/

