---

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: "{{ install_prefix }}/mit-testssl.sh/"

- name: Install python3-venv
  apt:
    pkg: python3-venv
  when: ansible_os_family == "Debian"

# Either 39 or 311
- name: Get python packaging prefix
  shell: pkg info|egrep -o "^python[0-9]{2,3}-"|egrep -o "[0-9]+"
  register: python_packaging_prefix
  changed_when: no
  when: ansible_os_family == "FreeBSD"

- name: Install python packaging {{ python_packaging_prefix.stdout }}
  package:
    name: py{{ python_packaging_prefix.stdout }}-packaging
  when: ansible_os_family == "FreeBSD"

- name: Install pip in venv
  pip:
    name: pip
    virtualenv: "{{ install_prefix }}/mit-testssl.sh/.venv"
    virtualenv_command: python3 -m venv

- name: Updated python dependencies (requirements.txt)
  pip:
    virtualenv_command: python3 -m venv
    requirements: "{{ install_prefix }}/mit-testssl.sh/requirements.txt"
    virtualenv: "{{ install_prefix }}/mit-testssl.sh/.venv"
  environment: "{{ proxy_env }}"

- name: "rsync testssl.sh (directory, distribution)"
  synchronize: 
    src: testssl.sh/
    dest: "{{ install_prefix }}/mit-testssl.sh/testssl.sh/"
    delete: yes
    rsync_opts:
      - "--exclude=.git"

- name: Copy wrapper scripts
  copy:
    src: "{{ item }}"
    dest: "{{ zabbix_server_externalscripts_path }}"
    mode: 0755
  loop:
    - mit-check-cert.py
    - mit-check-cert.sh

- name: Copy mit-testssl.sh*
  copy:
    src: "{{ item }}"
    dest: "{{ install_prefix }}/mit-testssl.sh/bin/"
    mode: 0755    
  loop:
    - mit-testssl.sh
    - mit-testssl.sh-caller
    - mit-testssl.sh-helper

- name: Remove deprecated files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/cron.d/local-zabbix-mit-testssl-caller
    - /etc/cron.d/local-zabbix-mit-testssl.sh-caller
    - /usr/local/bin/zabbix-mit-testssl
    - /usr/local/bin/zabbix-mit-testssl-caller
    - /usr/local/bin/zabbix-mit-testssl-helper
    #TODO - /usr/local/share/testssl.sh
    - /var/log/zabbix/zabbix-mit-testssl-caller.log

- name: "Copy cronjob"
  copy:
    # without dot as the dot prevents it from beeing executed
    src: local-zabbix-mit-testssl-sh-caller
    dest: /etc/cron.d/

